const ATTACK = 'ATTACK';
const DEFEND = 'DEFEND';
const PROPOSE_ECONOMIC_ALLIANCE = 'PROPOSE_ECONOMIC_ALLIANCE';
const PROPOSE_MILITARY_ALLIANCE = 'PROPOSE_MILITARY_ALLIANCE';

export default {
	ATTACK,
	DEFEND,
	PROPOSE_ECONOMIC_ALLIANCE,
	PROPOSE_MILITARY_ALLIANCE
};
