const DEFENSE_BONUS = 0.0;
const ATTACK_DAMAGE_BONUS = 0.0;
const MOVEMENT_SPEED_BONUS = 0.0;

const DEFAULT_DISTANCE_TIME = 8 * (1000 * 60); // 8 minutes in milliseconds

export default {
	DEFENSE_BONUS,
	ATTACK_DAMAGE_BONUS,
	DEFAULT_DISTANCE_TIME
};
