import Units from './units.js';

const BASE_UPGRADE_BONUS = 0.1;
const DEFENSE_BONUS = 0.0;
const ATTACK_DAMAGE_BONUS = 0.0;
const MOVEMENT_SPEED_BONUS = 0.0;

const CounterBonusDamage = {
	[Units.ARCHER.name]: 0.2,
	[Units.SPEARMAN.name]: 0.2,
	[Units.HORSEMAN.name]: 0.2
}

const DEFAULT_DISTANCE_TIME = 8 * (1000 * 60); // 8 minutes in milliseconds
const MORALE_MAX_DISTANCE_BLOCKS = 10;
const MORALE_DROP_PER_BLOCK = 10;
const MORALE_MAX_PENALTY = 0.13;
const MORALE_MIN_POINTS_MULTIPLIER = 1 - MORALE_MAX_PENALTY;

export default {
	DEFENSE_BONUS,
	BASE_UPGRADE_BONUS,
	ATTACK_DAMAGE_BONUS,
	DEFAULT_DISTANCE_TIME,
	MORALE_MAX_DISTANCE_BLOCKS,
	MORALE_DROP_PER_BLOCK,
	MORALE_MAX_PENALTY,
	MORALE_MIN_POINTS_MULTIPLIER,
	CounterBonusDamage
};
